apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gateway-crds.yaml
  - nginx-gateway-fabric.yaml
  - gatewayclass.yaml
  - externalsecret-cloudflare.yaml
  - gateway.yaml
  - referencegrant.yaml
