# HTTPRoute patch for production overlay
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-httproute
  labels:
    app.kubernetes.io/environment: production
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.yt-summarizer.apps.ashleyhollis.com
spec:
  hostnames:
  - "api.yt-summarizer.apps.ashleyhollis.com"
