# HTTPRoute patch for PR #5
# Generated for preview testing

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-httproute
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api-pr-5.yt-summarizer.apps.ashleyhollis.com
spec:
  hostnames:
  - "api-pr-5.yt-summarizer.apps.ashleyhollis.com"
