apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-httproute
  labels:
    app.kubernetes.io/name: yt-summarizer
    app.kubernetes.io/component: api
    app.kubernetes.io/environment: production
  annotations:
    # ExternalDNS watches this annotation to create DNS records
    external-dns.alpha.kubernetes.io/hostname: api.yt-summarizer.apps.ashleyhollis.com
spec:
  parentRefs:
  - name: main-gateway
    namespace: gateway-system
    sectionName: https
  hostnames:
  - "api.yt-summarizer.apps.ashleyhollis.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: api
      port: 8000
      weight: 100
